### ISSUE TITLE
自己紹介　田中歩

### ISSUE THREAD

**Issue by a-rom** [kurasawanko/team_project#3]
はじめまして。田中歩（たなかあゆむ）と申します。
株式会社リクルートホールディングスで新規事業開発をしています。

宜しくお願いします。

**Comment by kurasawanko** [comment]
@a-rom よろしくお願いします。
エンジニアの方ですか？

**Comment by a-rom** [comment]
@kurasawanko　主務はエンジニアではないです。ディレクターとかスクラムマスターをやる事が多いです。
