### ISSUE TITLE
自己紹介　Koala

### ISSUE THREAD

**Issue by juneqch** [kurasawanko/team_project#4]
Koala Cheungです。
よろしくお願いいたします。

**Comment by kurasawanko** [comment]
@a1624 よろしくお願いします！

**Comment by a-rom** [comment]
@a1624 宜しくお願いします。

**Comment by juneqch** [comment]
Close issue

**Comment by juneqch** [comment]
課題1: GitHubのIssue/Wikiを学ぶ

リポジトリのIssue機能を使ってみよう
一人1つIssueを登録する
メンバーのIssueに挨拶する（投稿する）
終わったらIssueを閉じてみる
